--- 
dist: xenial
language: node_js
node_js:
  - 13
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres PASSWORD 'password';" -U postgres
jobs:
  include:
    - stage: "set up parse server scheme"
      install: "cd attendance-server && npm install"
      script: 
        - "node index.js"
        - "python setup.py"
